### ISSUE TITLE
Search for mods from GitHub

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#1]
If the output is Modrinth or Packwiz, it's probably wise to consider non-CF sources as neither format currently supports the new API. So:

1) See if the mod is on Modrinth
2) If not, see if the mod has a GitHub issues link
    * If not, see if the mod has a GitHub source link
    * If not, see if the mod has a GitHub homepage link
3) If GitHub link is found, see if the mod has published releases
4) If yes, see if the releases have a matching jar
   * Matching could mean literal hash or any jar that is published with the same version number as the input.
5) If yes, use that jar url in modrinth/toml

Reference: https://stackoverflow.com/questions/18995854/how-can-i-use-github-api-to-get-all-tags-or-releases-for-a-project

**Comment by RozeFound** [comment]
Done with #4
