### ISSUE TITLE
Compute only the required hashes

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#12]
Pretty sure Modrinth only needs sha1 and sha512, but when I tried exporting to Modrinth format, you also included sha256 and murmur2, which just wastes computer resources and makes the file larger.

**Comment by RozeFound** [comment]
It will likely break file caching, and removing it will waste computer resources every time you use the script. With caching you anyway need to compute all the hashes only once per file (cache is consistent over reboots). But I can remove sha256 and murmur2 hashes from modrinth pack output, so it will not take extra space.
