### ISSUE TITLE
Prefer Modrinth over Github

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#13]
I used the command `mmc-export -i "C:\Users\Madis\Desktop\Fabulously Optimized 3.8.1.zip" -f Modrinth -o modpacks --exclude-providers cf` and found that GH links were found for some files, but they were listed _before_ Modrinth ones.

The latter should be preferred, as downloading from Modrinth increases the mods' download counts.

**Comment by RozeFound** [comment]
Isn't it a client work to choose right link?

**Comment by Madis0** [comment]
Pretty sure the client is supposed to pick the first link and if it doesn't work, then goes up to the next.

**Comment by RozeFound** [comment]
I just found that alphabetical sort works very well.
What about this order? `'cdn.modrinth.com', 'edge.forgecdn.net', 'github.com', 'media.forgecdn.net', 'raw.githubusercontent.com'`

**Comment by Madis0** [comment]
I'd say `'edge.forgecdn.net', 'media.forgecdn.net', 'cdn.modrinth.com', 'raw.githubusercontent.com', 'github.com'` would be a more logical approach.

**Comment by RozeFound** [comment]
I'm too lazy to manual sort it, I'll take alphabetical variant

**Comment by RozeFound** [comment]
`'media.forgecdn.net', 'raw.githubusercontent.com'` type of links is rare anyway, and modrinth links looks more viable for modrinth pack, so good compromise I think

**Comment by Madis0** [comment]
Fair enough.
