### ISSUE TITLE
Elaborate on Modrinth search methods

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#19]
The readme says this:
> --modrinth-search: modrinth search accuracy (exact (default), accurate, loose)

It would be great if there was more information in the readme regarding the different options. 

I think it works like that but please confirm:

* exact - by hash
* accurate - by hash or slug
* loose - by hash, slug or long name

**Comment by RozeFound** [comment]
You're right, mostly, loose is only hash and long name
