### ISSUE TITLE
Output Modrinth jars only for Modrinth and packwiz formats

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#2]
Because of the new Curseforge API, the script should now only list the mods that have a Modrinth matching jar (until you implement #1) for Modrinth and Packwiz output.

Mods that are not on Modrinth should be listed in the console window with issue or source links next to them (parsed from the jars' Fabric metadata).

**Note: if Modrinth decides to add support for Curseforge API, this should be reverted.**

**Comment by RozeFound** [comment]
#1 implemented with #4.
