### ISSUE TITLE
Add the way to remove losted mods

### ISSUE THREAD

**Issue by RozeFound** [RozeFound/mmc-export#27]
Add a key to config named "Action" with values "Remove, Ignore, Override"
Remove - totally delete resource from output packs 
Override - move resource to overrides (current behaviour), setting it explicitly will shut-up the warning
Ignore  - same as override, just for convenience

**Comment by Madis0** [comment]
> Ignore - same as override, just for convenience

Pretty sure you meant "same as remove". I would just keep "Ignore" and not do "Remove" as the former sounds more accurate. (you can't _remove_ something you haven't added, but you can _ignore_ it so you won't add it)

**Comment by RozeFound** [comment]
In this case I mean ignore warning, not the mod. But you're right it's not intuitive
