### ISSUE TITLE
Modrinth: log known repositories for bundled mods

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#35]
When exporting to Modrinth and linkable jars are not found for some mods, the script should continue to bundle them but also fetch source repo links (like #1) and post them to the terminal log.

Then the user could copy them into the changelog to be compliant with the mod licenses.
If a repo was not found, list any other known link (e.g. CurseForge listing)

Edit: separate GitHub links from other links to highlight the point that not any mod can be added unless the license allows.

As Modrinth uses Markdown, it could be instantly formatted as such:
```
Sources for bundled mods:

* [Mod1](https://github.com/user/mod1)
* [Mod2](https://github.com/user/mod2)
* [Mod3](https://github.com/user/mod3)

```

This is why:
https://blog.modrinth.com/modpack-changes/

**Comment by Madis0** [comment]
> PS C:\Users\Madis> mmc-export -i "C:\Users\Madis\Desktop\Fabulously Optimized 3.8.3 MR.zip" -f Modrinth -o "C:\Users\Madis\Desktop" --exclude-providers CurseForge --modrinth-search loose
59/60 GitHub searches remaining, after that only cached results will be used.
To get more searches, sign in with mmc-export gh-login or wait until 22:18 to get 60 searches again.
Specify modpack version: 3.8.3-mr.2
No config entry found for resource: CIT Resewn
No config entry found for resource: Cloth API
No config entry found for resource: Cloth Config v6
No config entry found for resource: DCCH
No config entry found for resource: Fabric Language Kotlin
No config entry found for resource: Farsight Mod
No config entry found for resource: Not Enough Crashes
No config entry found for resource: ToolTip Fix
No config entry found for resource: YOSBR
No config entry found for resource: Mod Menu Helper

The mods that gave warnings were properly placed in the result zip, but `bundled_links.md` contents were empty:

```
Sources for bundled mods:

GitHub links


Other links


Always check the licenses to see if they allow distribution!
```

**Comment by RozeFound** [comment]
Because it was bundled on config parseing stage, to get bundled links you must enable CF as well
