### ISSUE TITLE
Warn if GitHub API limit has been reached

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#36]
When the GitHub API limit has been reached and the user is not signed in, warn something like this:

> You have exceeded the GitHub API limit, no further GitHub searches can be made right now. Please sign in with `command` or try again at 12:34.

I guess it can still work by the cache so you can improve the message as needed.

**Comment by RozeFound** [comment]
I can't make it to non-batched request due to async nature, and for batched it's useless because you probably never hit rate limit with batched request. All I can offer is to print ratelimit remaining before non-bathched requests

**Comment by Madis0** [comment]
So what happens in code if the GitHub requests fail?

**Comment by RozeFound** [comment]
It will be silently skipped

**Comment by Madis0** [comment]
Okay. How about:

> 20/50 GitHub searches remaining, after that only cached results will be used. To get more searches, sign in with `command` or wait until 12:34 to get 50 searches again.

**Comment by RozeFound** [comment]
Oh actually I found the way to warn user after non-batched requests, in decostructor lol

**Comment by RozeFound** [comment]
But, I can combine these methods

**Comment by Madis0** [comment]
Sure, let's try combined.
