### ISSUE TITLE
Messed up config folder

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#37]
Tried version 2.3.0.

Input file structure:

- mods
    - (some mods)
- resourcepacks
    - (some resourcepacks) 
- config
    - (some files 1)
    - yosbr
        - config
            - (some files 2)
        - options.txt

Output file structure:

- config
   - (some files 1)
   - (some files 2)
- mods
    - (some mods)
- resourcepacks
     - (some resourcepacks)
- yosbr
   - options.txt

**Comment by RozeFound** [comment]
Must be fixed now
