### ISSUE TITLE
GitHub searches don't decrease

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#39]
Using 2.3.0 with this command:
> mmc-export -i "C:\Users\Madis\Desktop\Fabulously Optimized 3.8.3 MR.zip" -f Modrinth -o "C:\Users\Madis\Desktop\" --exclude-providers CurseForge --modrinth-search loose

and every launch gives me this result again:

> 59/60 GitHub searches remaining, after that only cached results will be used.
To get more searches, sign in with `mmc-export gh-login` or wait until 22:18 to get 60 searches again.

Considering that I am not signed in and there are links in modrinth.index.json, it doesn't seem possible that it only ran one request. And even then, why does it not repeat the request the next time I use the command, while the API limits haven't been reached?

**Comment by RozeFound** [comment]
After first launch, all results are cached, except failed ones, this means if you 1 mod failed to even search on GitHub (broken url for example), it will try to make request every launch to get successful result and cache it.

**Comment by Madis0** [comment]
Okay, but how come it only used one search if I am not signed in? I think you said that only signed in users get batch requests?

**Comment by RozeFound** [comment]
I didn't specified cache expire time, maybe it's too big so it doesn't expire from last launch, or, library I use finally implements 302 codes handling and requested resources didn't changed from last launch

**Comment by Madis0** [comment]
Fair enough.
