### ISSUE TITLE
Version as parameter

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#45]
The modpack version can be defined in the config or prompted by the script. Now what about a parameter like `--version 1.2.3`?

**Comment by RozeFound** [comment]
Lol why

**Comment by RozeFound** [comment]
You feel like these two methods are not enough?

**Comment by Madis0** [comment]
If I start using your script in my main workflow of https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/CLI%20tools/CurseForge%20to%20Packwiz-Modrinth.py , I would have to open, write, save the script every time... or I could just remove the version from config and pass a parameter 🙃

**Comment by RozeFound** [comment]
Hmm. Yeah makes sense in automated workflow
