### ISSUE TITLE
Resource definition: "latest"

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#46]
Use case:

I have a mod that updates fast on CurseForge and slow on Modrinth. When I create a Modrinth pack, I can either choose to bundle the latest mod or get an older one from Modrinth. (The latest would be good if there are bugfixes but older is good for getting the dev downloads and credit.)

So, when I decide to use the older version, I have to define an override in the config. But that override is a static URL, who knows when that mod will get updates on Modrinth again...

Solution:

A config definition like this

```
[[Resource]]
name = "ModName"
Minecraft = "1.18.2"
provider =  "Modrinth"
action = "latest"
```

That would mean the script either gets the latest version from Modrinth or, if one doesn't exist for that Minecraft version, just bundles it.
You might be able to make this work for GitHub and CurseForge (for other export formats like packwiz) as well or use a slug instead of the mod name, that's up to you.

**Comment by RozeFound** [comment]
Okay I'll leave it open, but I don't want to implement it myself. I would appreciate a PR on this.
