### ISSUE TITLE
"No config entry found" when skipping CurseForge

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#48]
On 2.3.4, using this command shows no output
```
mmc-export -i "C:\Users\Madis\Desktop\Fabulously Optimized 3.8.3 MR.zip" -f Modrinth -o "C:\Users\Madis\Desktop\" --modrinth-search loose --config "C:\Users\Madis\Documents\GitHub\fabulously-optimized\Modrinth\mmc-export.toml"
```
but using this one shows "no config entry" warnings
```
mmc-export -i "C:\Users\Madis\Desktop\Fabulously Optimized 3.8.3 MR.zip" -f Modrinth -o "C:\Users\Madis\Desktop\" --modrinth-search loose --config "C:\Users\Madis\Documents\GitHub\fabulously-optimized\Modrinth\mmc-export.toml" --exclude-providers CurseForge
No config entry found for resource: Cloth API
No config entry found for resource: Fabric Language Kotlin
No config entry found for resource: ToolTip Fix
No config entry found for resource: YOSBR
````

Both commands use the same config: https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/Modrinth/mmc-export.toml
and have the same amount of overridden mods
![image](https://user-images.githubusercontent.com/8611110/171449326-7a78490d-039a-4a27-8fd9-6183712aaed7.png)

**Comment by RozeFound** [comment]
It's happening because more mods without any providers was found, and you must specify what to do with it in config.
