### ISSUE TITLE
Difference between "ignore" and "override"?

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#49]
I've noticed that the readme now has both "Hide the warning" and "Explicitly move to overrides". What's the difference?

When you hide the warning but don't delete the mod, shouldn't it also move it to overrides?

**Comment by RozeFound** [comment]
Yes, but "ignore" will leave it to writers, and they will decide move this file to overrides or not, but if you specify "override", you explicitly tells to override this mod even if it has download links and can be used as resource

**Comment by Madis0** [comment]
Ah, right so ignore basically would work like in #48 for Modrinth. Makes sense.
