### ISSUE TITLE
Few incorrect hashes

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#51]
2.3.6
`mmc-export -i "c:/Users/Madis/Desktop/Fabulously Optimized 3.9.0.zip" -f Modrinth --modrinth-search loose -o "c:/Users/Madis/Desktop/" -c "C:/Users/Madis/Documents/GitHub/fabulously-optimized/Modrinth/mmc-export.toml" -v 3.9.0`
![image](https://user-images.githubusercontent.com/8611110/171988863-a80c02a5-0c58-4f5c-840c-4d45d2e087eb.png)
[modrinth.index.json.txt](https://github.com/RozeFound/mmc-export/files/8837206/modrinth.index.json.txt)

same happens when importing FO 3.9.1 btw

**Comment by RozeFound** [comment]
Can you send intermediate output?

**Comment by Madis0** [comment]
[intermediate_output.json.txt](https://github.com/RozeFound/mmc-export/files/8837288/intermediate_output.json.txt)

**Comment by Madis0** [comment]
Actually, reading the error it just seems the script doesn't like (anymore?) when a version has two files - a jar for users and a sources jar.

**Comment by RozeFound** [comment]
Yeah, I think that's the problem. It never liked when a version have multiple files

**Comment by RozeFound** [comment]
Fixed with latest?

**Comment by Madis0** [comment]
Fixed with latest.
