### ISSUE TITLE
Do not import .disabled mods

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#53]
or idk, do something with them so they don't appear in Modrinth output

**Comment by RozeFound** [comment]
Oh Yeah, I forgot that MMC can disable mods.
You can just not export them, when you do this with MMC, till I fix it

**Comment by Madis0** [comment]
Actually, I was thinking about this - CurseForge and packwiz do support disabled mods, so they should still get it as optional ones.

**Comment by Madis0** [comment]
Well, in that case CurseForge still supports disabled mods, only packwiz has the concept of "optional" mods.

**Comment by Madis0** [comment]
Bump to remind that CF output still should get the disabled mods.

**Comment by RozeFound** [comment]
What do you mean?

**Comment by Madis0** [comment]
I mean CurseForge still has the concept of disabled mods, just like MultiMC, so these should be included in CF output as disabled.

E.g.

```
{
      "projectID": 400322,
      "fileID": 3684228,
      "required": false
}
```

**Comment by RozeFound** [comment]
Still, is there any reason?

**Comment by RozeFound** [comment]
But of it's disabled, this means that it's not wanted for a reason.
