### ISSUE TITLE
Resource definition: "optional"

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#54]
Allow marking certain mods as optional in the config.

This would behave:

* As disabled when exported to CurseForge
* As optional when exported to packwiz
* As env optional when exported to Modrinth:

```
"env": {
    "client": "optional",
    "server": "optional"
}
```

**Comment by RozeFound** [comment]
Is there any reason to?

**Comment by Madis0** [comment]
It could complement #53 for people who want to include disabled mods in the modpacks after all. I don't need it at the moment though, just throwing out the idea.

**Comment by RozeFound** [comment]
Meh, I don't think it's useful. I personally never seen modpacks with optional mods, so doesn't seems like this feature really used by anyone. 
I'll leave it open, and if someone who needs this feature exists in this world, leave a comment and I'll implement it.
