### ISSUE TITLE
Check for a license in GitHub

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#55]
Assuming it is not too hard, the script could also check for the presence of a license file in a GitHub repo when importing mods from it. 
The contents don't matter, just that there should be a `license.md`, `LICENSE.txt` or any other format GitHub recognizes.

Then that could be written as a warning next to the row in linked_mods.md, or possibly as a separate category altogether ("GitHub mods without license"?).

**Comment by RozeFound** [comment]
What's the point?

**Comment by Madis0** [comment]
The point is to not accidentally include mods that are not FOSS, but instead source-available ARR.

**Comment by RozeFound** [comment]
I can get info about license shown in right corner of the page, but not more than that. And it will cost another API call, so will decrease amount of mods that can be searched on GitHub with unauthorized access from 60 to 30, and it's near unusable

**Comment by RozeFound** [comment]
Is it really worth it?

**Comment by RozeFound** [comment]
30 requests is kinda useless, so if I willing to implement this, I'll probably remove unauthorized version.
Which is not good idea, because not everyone have GitHub account nor want to authorize with it in some random CLI app.
