### ISSUE TITLE
Config doesn't overrides resource providers

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#63]
![image](https://user-images.githubusercontent.com/8611110/189709120-cab2a727-4e8b-4ec5-b66d-696e91bd3ee2.png)

[Overrides](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/packwiz-test/Modrinth/mmc-export.toml)

Or wait, isn't it actually #61 again? Because it should've not ported Farsight to packwiz format in the first place, [but it did](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/packwiz-test/Packwiz/1.19.2/mods/farsight-fabric.pw.toml)...

**Comment by RozeFound** [comment]
What command did you used for generating such output?

**Comment by Madis0** [comment]
```
mmc-export -i "...\Fabulously Optimized 4.3.1.zip" -f packwiz --modrinth-search loose -o "...\outputfolder" -c "...\fabulously-optimized\Modrinth\mmc-export.toml" -v 4.3.1-pw.1 --scheme "{abbr}_{name}_{version}" --provider-priority Modrinth, CurseForge, Other
```

**Comment by RozeFound** [comment]
Well, that's why it was added. You put CurseForge higher priority than `Other` which is apparently your config

**Comment by RozeFound** [comment]
And separator must be space, not comma

**Comment by Madis0** [comment]
> Well, that's why it was added. You put CurseForge higher priority than `Other` which is apparently your config

Err.. but what if I want overrides to be the first in priority, but GitHub to be the last? The readme says they are interchangeable...

So basically `Other Modrinth CurseForge GitHub` I guess.

**Comment by RozeFound** [comment]
Uh, that's impossible unfortunately. `GitHub` and `Other` are just aliases to each other.
But, I can change how config works, so it will completely replace providers instead of just adding one

**Comment by Madis0** [comment]
So you can make it possible? I didn't quite understand.

It doesn't seem that hard in theory, `Other` would only read the `mmc-export.toml` and `GitHub` would ping its API.

**Comment by RozeFound** [comment]
Um... That's not quite how this works, but I can fix your issue

**Comment by RozeFound** [comment]
Must work properly now with `--provider-priority Modrinth CurseForge Other`
