### ISSUE TITLE
Match packwiz format as closely as possible

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#64]
for easier diffs and overall format compatibility. In all pictures **red is generated by packwiz and green is generated by mmc-export**.

E.g. in mod file the order of update-download and the `side`:

![image](https://user-images.githubusercontent.com/8611110/189712413-0837ecd0-b37e-4106-a519-d4d382fdfd79.png)

in index.toml the slashes (mod files already use `/` consistently!):

![image](https://user-images.githubusercontent.com/8611110/189712806-74681006-00fa-4437-81ef-05e874574c2f.png)
![image](https://user-images.githubusercontent.com/8611110/189712857-580da176-8e07-4994-869d-9caa02406531.png)

and in pack.toml there should be the format version:

![image](https://user-images.githubusercontent.com/8611110/189713196-393bcd52-41ae-4128-a722-82e0d7bca432.png)

**Comment by RozeFound** [comment]
Oh, my bad, I accidentally let path's be OS-dependent. 
Side is... Do you really need it? I removed it from everywhere because it's useless mostly.
Order... Well, I can change the order if it's so important.

**Comment by RozeFound** [comment]
But it's optional anyway...

**Comment by RozeFound** [comment]
Well, okay. If I'll just add `side = "both"` without really trying to determine side will be enough?

**Comment by Madis0** [comment]
Yeah, that's what packwiz already does I think.
