### ISSUE TITLE
Config ignores plain files

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#65]
I made an empty file "Copy all 3 folders!" (yes, it has an exclamation mark and no file extension) and [defined mmc-export.toml](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/Modrinth/mmc-export.toml) as

```
[[Resource]]
name = "Copy all 3 folders!"
filename = "Copy all 3 folders!"
action = "remove"
```

mmc-export did not ignore the file.

**Comment by RozeFound** [comment]
It doesn't dislike weird filenames, it's just don't do shit about plain files ¯\_(ツ)_/¯
This filed is for resources what you can guess by label `[[Resource]]`, which is mods, resource-packs and shader-packs
So that's why your wasn't noticed by config parser

**Comment by Madis0** [comment]
Ehhhhh... makes sense, but y'know, would be nice to use "remove" for any file 😆

**Comment by RozeFound** [comment]
I thought users won't include files thy don't need in the first place, during exporting an MMC pack, but... Well, I can add an option to remove any file

**Comment by RozeFound** [comment]
Can I ask you to update description before I publish it to pip?
