### ISSUE TITLE
"minecraft" folder can be ".minecraft"

### ISSUE THREAD

**Issue by Brancieq-Paul** [RozeFound/mmc-export#68]
Hi ! In a recent update (0.6.0), multiMC changed the default name of the instance directory from "minecraft" to ".minecraft". Instances with "minecraft" directory are still supported but new ones are now created with the dot.

The problem with mmc-export is in "parser.py", line 51. Here you only accept "minecraft" folders for the overrides, so we can't export overrides from modern instances.

It should be able to read either from "minecraft" or ".minecraft".

**Comment by RozeFound** [comment]
As far as I remember it always was `.minecraft` at least in windows. And pathlib handles everything without any problems.
Does it actually throw any errors?

**Comment by Madis0** [comment]
Can confirm that using `.minecraft` instead of `minecraft` will make mmc-export ignore `config` folder in the Modrinth export.

**Comment by RozeFound** [comment]
Can someone please test latest patch? I have some problems with my current dev environment, so I can't do it myself.

**Comment by Madis0** [comment]
Works for me now.

**Comment by RozeFound** [comment]
So, I guess I can close the issue now? I'll wait till tomorrow for more responses, if nothing happen I'll close it.
