### ISSUE TITLE
Having Jade in a pack errors when exporting due to the magnifying glass character.

### ISSUE THREAD

**Issue by Verbina29** [RozeFound/mmc-export#71]
`UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f50d' in position 13: character maps to <undefined>` seems to be the relevant part of the error.
Note that I only tried packwiz export. [Link to Jade.](https://modrinth.com/mod/jade)

**Comment by RozeFound** [comment]
Hm. Works fine for me. What OS do you use?
If it's possible, can you send me a modpack you trying to export and config for mmc-export if you have one?

**Comment by Verbina29** [comment]
Windows 10. Happens with a pack with only Jade and QSL, and without a config.
[mmc-export-test.zip](https://github.com/RozeFound/mmc-export/files/11274720/mmc-export-test.zip)

**Comment by RozeFound** [comment]
Might be a windows issue with representing unicode characters then.
What mmc-export version do you use?

**Comment by Verbina29** [comment]
Just downloaded it today, so the latest version.

**Comment by RozeFound** [comment]
The issue was me being dumb, must be fixed in 2.8.3, please update and report if your issue is gone
