### ISSUE TITLE
File deletition doesn't seem to work

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#72]
https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/CLI%20tools/CurseForge%20to%20Packwiz-Modrinth.py
https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/Modrinth/mmc-export.toml#L32
![image](https://user-images.githubusercontent.com/8611110/233700717-8c94266c-d0fb-4a7c-9d54-2c17c0d70278.png)

It worked before, when the file was named `Copy all 3 folders!` (no file extension).

MMC-export 2.7.4, win11

**Comment by RozeFound** [comment]
`name` in `[[File]]` is the actual file name, `filename` field does nothing
