### ISSUE TITLE
Weird characters in project name break mmc-export

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#73]
Basically https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters happens when trying to get the project names for packwiz.

> UnicodeEncodeError: 'charmap' codec can't encode character '\u200b' in position 8: character maps to <undefined>

I've actually fixed the character on my end on the project itself, but the issue still remains while it is on the CDN 😩

**Comment by RozeFound** [comment]
Huh? I'm sure I fixed it not so long ago

**Comment by RozeFound** [comment]
Are you using latest version?
Can you give me full traceback?

**Comment by Madis0** [comment]
After getting the issue, I updated to the latest version and retried, it occurred again. The full traceback didn't seem to mention mmc-export traces in detail, instead it mentioned the Python exe so it didn't seem useful.

I worked around the issue by using --skip-cache and a source location override, so I'm not sure if I can give any more helpful data at this point.

**Comment by RozeFound** [comment]
How can I reproduce it?

**Comment by Madis0** [comment]
Add `\u200b` aka `​` to an online project name and try to export it as packwiz and/or modrinth.

**Comment by RozeFound** [comment]
I don't quite understand what do you mean by that

**Comment by Madis0** [comment]
I had a CurseForge project that had this character in the name, so every time mmc-export tried to pull the data, this error occurred and the export did not complete.

**Comment by RozeFound** [comment]
Well, I guess it's some weird edge case which I don't even understand why happening, because I'm sure I fixed all encoding related issues for packwiz ¯\\_(ツ)\_/¯
Cache files shouldn't be affected either, since this type of data is not cached. 
So my conclusion is that this issue is related to something else, and without comprehensive info or the ability to replicate the issue, I won't be able to fix it.

**Comment by Madis0** [comment]
Okay, I'm gonna close it for now.

**Comment by RozeFound** [comment]
Be sure to gather more info if you encounter it again!
