### ISSUE TITLE
Disabled/optionals not working properly

### ISSUE THREAD

**Issue by Brancieq-Paul** [RozeFound/mmc-export#93]
Disabled mods become optionals in .mrpacks.

But if you have .disabled override, mmc-export remove the .disabled fiel extension. It would be great to keep it.

**Comment by RozeFound** [comment]
Unfortunately removal of .disabled extension happens quite early in the conversion process so everything would work correctly. It would be troublesome to keep this extension at any stage of the process. It can be re-added with a condition somewhere [here](https://github.com/RozeFound/mmc-export/blob/651c399141bac5e052ecebd21883655cab6943e2/mmc_export/Formats/modrinth.py#L105), but I don't think this is a good solution.

**Comment by RozeFound** [comment]
If you think that this is critical bug then I'll fix it, otherwise I'll just leave it as wontfix.

**Comment by Brancieq-Paul** [comment]
Yeah, a togle "isDisabled" in the resource and something to add the extension back in the add_override method if true.

I don't think it is critical but if it's not implemented in there, I will have to make my own quick script to put the extension back in the .mrpack.

It's as you wish.

**Comment by RozeFound** [comment]
Hmm. It does sounds reasonable to keep the original filenames in overrides.

**Comment by RozeFound** [comment]
Should be fixed now.
